import {
  PERMISSION_KEYS,
  PERMISSIONS,
  type PermissionDefinition,
  type PermissionGrant,
  type PermissionKey,
  type PermissionScope,
} from './permissions';

/**
 * System role templates, copied into every new tenant. Tenants may clone and adjust them, and
 * system roles can be disabled but not deleted. Matrix: docs/architecture/03-rbac.md §4.
 */
export interface RoleTemplate {
  readonly key: string;
  readonly name: string;
  readonly description: string;
  readonly external: boolean;
  readonly grants: readonly PermissionGrant[];
}

const grant = (scope: PermissionScope, ...permissions: PermissionKey[]): PermissionGrant[] =>
  permissions.map((permission) => ({ permission, scope }));

const byAction = (predicate: (key: PermissionKey, def: PermissionDefinition) => boolean): PermissionKey[] =>
  PERMISSION_KEYS.filter((key) => predicate(key, PERMISSIONS[key]));

const READ_ACTIONS = /\.(read|export)$/;
const isRead = (key: PermissionKey) => READ_ACTIONS.test(key);
/** Pick the widest scope a permission allows, preferring ALL. */
const widest = (key: PermissionKey): PermissionScope => {
  const scopes: readonly PermissionScope[] = PERMISSIONS[key].scopes;
  return scopes.includes('ALL') ? 'ALL' : scopes[0]!;
};
const atWidest = (keys: PermissionKey[]): PermissionGrant[] =>
  keys.map((permission) => ({ permission, scope: widest(permission) }));

/** Actions that belong to the external party, never to internal admins. */
const EXTERNAL_PARTY_ACTIONS: PermissionKey[] = ['study.decide', 'production.update_status'];

export const ROLE_TEMPLATES: readonly RoleTemplate[] = [
  {
    key: 'company_admin',
    name: 'Company Admin',
    description: 'Manages users, settings, permissions and company configuration.',
    external: false,
    grants: atWidest(byAction((key) => !EXTERNAL_PARTY_ACTIONS.includes(key))),
  },
  {
    key: 'management',
    name: 'Management',
    description: 'Visibility over campaigns, clients, commercial data, operations and reports.',
    external: false,
    grants: [
      ...atWidest(byAction((key) => isRead(key))),
      ...grant('ALL', 'opportunity.reopen', 'campaign.cancel', 'comment.create', 'comment.internal'),
      ...grant('ALL', 'ai.assistant.use', 'ai.suggestion.resolve'),
    ],
  },
  {
    key: 'ooh_buyer',
    name: 'OOH Buyer / Account Manager',
    description: 'Briefs, campaigns, research, studies, client approvals and field operations.',
    external: false,
    grants: grant(
      'ALL',
      'organisation.read',
      'organisation.create',
      'organisation.update',
      'contact.read',
      'contact.create',
      'contact.update',
      'opportunity.read',
      'activity.read',
      'activity.create',
      'activity.update',
      'brief.read',
      'brief.create',
      'brief.update',
      'brief.confirm',
      'brief.convert',
      'brief.discard',
      'campaign.read',
      'campaign.create',
      'campaign.update',
      'campaign.cancel',
      'campaign.export',
      'campaign_location.read',
      'campaign_location.manage',
      'asset.read',
      'asset.create',
      'asset.update',
      'asset.export',
      'asset.terms.read',
      'asset.verify',
      'asset.availability.manage',
      'research.read',
      'research.manage',
      'study.read',
      'study.manage',
      'study.publish',
      'study.decide_on_behalf',
      'production.read',
      'production.manage',
      'field_job.read',
      'field_job.manage',
      'field_job.assign',
      'evidence.read',
      'evidence.review',
      'tariff.read',
      'commercial.cost.read',
      'commercial.revenue.read',
      'commercial.margin.read',
      'commercial.write',
      'task.read',
      'task.create',
      'task.update',
      'calendar.read',
      'dashboard.read',
      'report.read',
      'report.export',
      'file.read',
      'file.upload',
      'comment.read',
      'comment.create',
      'comment.internal',
      'audit.read',
      'ai.assistant.use',
      'ai.suggestion.resolve',
    ),
  },
  {
    key: 'sales',
    name: 'Sales',
    description: 'Prospects, opportunities, activities, follow-ups and the sales pipeline.',
    external: false,
    grants: [
      ...grant(
        'ALL',
        'organisation.read',
        'organisation.create',
        'contact.read',
        'contact.create',
        'opportunity.read',
      ),
      ...grant('ALL', 'opportunity.create', 'activity.read', 'activity.create', 'brief.read', 'brief.create'),
      ...grant('OWN', 'organisation.update', 'organisation.export', 'contact.update', 'contact.export'),
      ...grant('OWN', 'opportunity.update', 'opportunity.close', 'activity.update'),
      ...grant('ALL', 'campaign.read', 'campaign_location.read', 'asset.read'),
      ...grant(
        'ALL',
        'task.read',
        'task.create',
        'task.update',
        'calendar.read',
        'dashboard.read',
        'report.read',
      ),
      ...grant('ALL', 'file.read', 'file.upload', 'comment.read', 'comment.create', 'comment.internal'),
      ...grant('ALL', 'ai.assistant.use', 'ai.suggestion.resolve'),
    ],
  },
  {
    key: 'finance',
    name: 'Finance / Commercial',
    description: 'Tariffs, costs, revenues, margins and invoicing-related data.',
    external: false,
    grants: grant(
      'ALL',
      'organisation.read',
      'contact.read',
      'opportunity.read',
      'brief.read',
      'campaign.read',
      'campaign.export',
      'campaign_location.read',
      'asset.read',
      'asset.terms.read',
      'asset.terms.manage',
      'research.read',
      'study.read',
      'production.read',
      'field_job.read',
      'evidence.read',
      'tariff.read',
      'tariff.manage',
      'tariff.publish',
      'commercial.cost.read',
      'commercial.revenue.read',
      'commercial.margin.read',
      'commercial.write',
      'commercial.lock',
      'task.read',
      'task.create',
      'task.update',
      'calendar.read',
      'dashboard.read',
      'report.read',
      'report.export',
      'file.read',
      'file.upload',
      'comment.read',
      'comment.create',
      'comment.internal',
      'audit.read',
      'ai.assistant.use',
      'ai.suggestion.resolve',
    ),
  },
  {
    key: 'production_manager',
    name: 'Production Manager',
    description: 'Coordinates print production and production suppliers.',
    external: false,
    grants: grant(
      'ALL',
      'organisation.read',
      'contact.read',
      'campaign.read',
      'campaign_location.read',
      'asset.read',
      'study.read',
      'production.read',
      'production.manage',
      'production.send',
      'production.complete',
      'field_job.read',
      'evidence.read',
      'commercial.cost.read',
      'task.read',
      'task.create',
      'task.update',
      'calendar.read',
      'dashboard.read',
      'report.read',
      'file.read',
      'file.upload',
      'comment.read',
      'comment.create',
      'comment.internal',
      'ai.assistant.use',
    ),
  },
  {
    key: 'decorator',
    name: 'Decorator / Installation Team',
    description: 'Mobile access to assigned jobs; uploads installation and removal evidence.',
    external: true,
    grants: grant(
      'ASSIGNED',
      'field_job.read',
      'field_job.execute',
      'evidence.read',
      'evidence.upload',
      'asset.read',
      'asset.verify',
      'task.read',
      'task.update',
      'calendar.read',
      'file.read',
      'file.upload',
    ),
  },
  {
    key: 'production_supplier',
    name: 'Production Supplier',
    description: 'Receives production orders and may update production status.',
    external: true,
    grants: grant(
      'ORGANISATION',
      'production.read',
      'production.update_status',
      'file.read',
      'comment.read',
      'comment.create',
    ),
  },
  {
    key: 'ooh_supplier',
    name: 'OOH Supplier',
    description: 'Provides rented/subleased advertising inventory.',
    external: true,
    grants: grant('ORGANISATION', 'asset.read', 'file.read', 'comment.read', 'comment.create'),
  },
  {
    key: 'agency_user',
    name: 'Agency User',
    description: 'Accesses campaigns for the clients managed by the agency.',
    external: true,
    grants: grant(
      'ORGANISATION',
      'campaign.read',
      'campaign.export',
      'campaign_location.read',
      'study.read',
      'study.decide',
      'evidence.read',
      'report.read',
      'report.export',
      'file.read',
      'comment.read',
      'comment.create',
    ),
  },
  {
    key: 'end_client',
    name: 'End Client',
    description: 'Accesses its own campaigns, approves proposed positions and views results.',
    external: true,
    grants: grant(
      'ORGANISATION',
      'campaign.read',
      'campaign.export',
      'campaign_location.read',
      'study.read',
      'study.decide',
      'evidence.read',
      'report.read',
      'report.export',
      'file.read',
      'comment.read',
      'comment.create',
    ),
  },
  {
    key: 'viewer',
    name: 'Read-only / Viewer',
    description: 'Restricted reporting access.',
    external: false,
    grants: grant(
      'ALL',
      'campaign.read',
      'campaign_location.read',
      'asset.read',
      'calendar.read',
      'dashboard.read',
      'report.read',
    ),
  },
];
