import { createHmac, timingSafeEqual } from 'node:crypto';
import { mkdir, readFile, stat, writeFile } from 'node:fs/promises';
import { dirname, join, resolve, sep } from 'node:path';
import { contentDisposition, type FileStorage, type PresignedUpload } from './storage';

/** What a local "presigned" URL allows (signed, expiring). */
export interface StorageGrant {
  /** Object key. */
  k: string;
  m: 'PUT' | 'GET';
  /** Expiry, epoch seconds. */
  e: number;
  /** PUT: the exact content type and size; GET: the download name and type. */
  t: string;
  s?: number;
  n?: string;
}

/** Path of local storage URLs under the API prefix (served by LocalStorageController). */
export const LOCAL_STORAGE_PATH = 'storage';

/**
 * Development storage on the local disk. URLs point at the API (`/api/v1/storage?token=…`) and carry
 * an HMAC-signed grant, so clients follow exactly the presigned-URL flow they use against S3.
 */
export class LocalFileStorage implements FileStorage {
  private readonly root: string;

  constructor(
    directory: string,
    private readonly secret: string,
    private readonly now: () => number = () => Date.now(),
  ) {
    this.root = resolve(directory);
  }

  presignPut(input: {
    key: string;
    contentType: string;
    sizeBytes: number;
    expiresIn: number;
  }): Promise<PresignedUpload> {
    const token = this.sign({
      k: input.key,
      m: 'PUT',
      e: this.expiry(input.expiresIn),
      t: input.contentType,
      s: input.sizeBytes,
    });
    return Promise.resolve({
      url: `/api/v1/${LOCAL_STORAGE_PATH}?token=${token}`,
      headers: { 'content-type': input.contentType },
    });
  }

  presignGet(input: {
    key: string;
    fileName: string;
    contentType: string;
    expiresIn: number;
  }): Promise<string> {
    const token = this.sign({
      k: input.key,
      m: 'GET',
      e: this.expiry(input.expiresIn),
      t: input.contentType,
      n: input.fileName,
    });
    return Promise.resolve(`/api/v1/${LOCAL_STORAGE_PATH}?token=${token}`);
  }

  async head(key: string): Promise<{ sizeBytes: number } | null> {
    try {
      return { sizeBytes: (await stat(this.pathOf(key))).size };
    } catch {
      return null;
    }
  }

  read(key: string): Promise<Buffer> {
    return readFile(this.pathOf(key));
  }

  async write(key: string, body: Buffer): Promise<void> {
    const path = this.pathOf(key);
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, body);
  }

  /** The grant in a token, or null when tampered with or expired. */
  verify(token: string, method: 'PUT' | 'GET'): StorageGrant | null {
    const [payload, signature] = token.split('.');
    if (!payload || !signature) return null;
    const expected = this.hmac(payload);
    const given = Buffer.from(signature, 'base64url');
    if (given.length !== expected.length || !timingSafeEqual(given, expected)) return null;
    const grant = JSON.parse(Buffer.from(payload, 'base64url').toString()) as StorageGrant;
    if (grant.m !== method || grant.e * 1000 < this.now()) return null;
    return grant;
  }

  disposition(grant: StorageGrant): string {
    return contentDisposition(grant.n ?? 'file');
  }

  private sign(grant: StorageGrant): string {
    const payload = Buffer.from(JSON.stringify(grant)).toString('base64url');
    return `${payload}.${this.hmac(payload).toString('base64url')}`;
  }

  private hmac(payload: string): Buffer {
    return createHmac('sha256', `local-storage:${this.secret}`).update(payload).digest();
  }

  private expiry(seconds: number): number {
    return Math.floor(this.now() / 1000) + seconds;
  }

  /** Keys are generated by the API; still, never let one escape the storage directory. */
  private pathOf(key: string): string {
    const path = resolve(join(this.root, key));
    if (!path.startsWith(this.root + sep)) throw new Error('Invalid storage key');
    return path;
  }
}
