import { sql } from 'drizzle-orm';
import { customType, integer, timestamp, uuid } from 'drizzle-orm/pg-core';

/** Case-insensitive text (PostgreSQL `citext` extension), used for emails. */
export const citext = customType<{ data: string }>({
  dataType: () => 'citext',
});

/** Primary key: time-ordered UUIDv7 generated by PostgreSQL 18 (`uuidv7()`). */
export const primaryId = () =>
  uuid('id')
    .primaryKey()
    .default(sql`uuidv7()`);

export const tenantIdColumn = () => uuid('tenant_id').notNull();

export const timestamps = () => ({
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
});

/** Optimistic-locking counter; exposed to clients as the ETag. */
export const versionColumn = () => integer('version').notNull().default(1);

export const archivedAt = () => timestamp('archived_at', { withTimezone: true });

/**
 * A WGS84 point as PostGIS `geography(Point, 4326)`. Write with `pointValue(lat, lng)` and read
 * coordinates with `ST_Y/ST_X(col::geometry)`; the raw driver value (EWKB hex) is not used.
 */
export const geographyPoint = customType<{ data: string; driverData: string }>({
  dataType: () => 'geography(Point,4326)',
});
